### ISSUE TITLE
Extension break when $owner have multiple primary key

### ISSUE THREAD

**Issue by rizkiarm** [2amigos/yii2-taggable-behavior#11]
Hi,
I'm experiencing some problem in using your extension when i have a table with multiple primary key that have a relationship with tag table. The extension breaks the QueryBuilder because it is trying to insert an associative array into the relationship table rather than inserting an id.

Currently, i;m handling this problem by using this quick fix:

```
$owner_primary_key = $this->owner->getPrimaryKey();
if(is_array($owner_primary_key)){
        $owner_primary_key = reset($owner_primary_key);
 }
 $rows[] = [$owner_primary_key, $tag->getPrimaryKey()];
```

If you have a better solution or fix for this problem, i'll be very happy to use it.

**Comment by tonydspaniard** [comment]
@creocoder is this issue taken care of?

**Comment by creocoder** [comment]
@tonydspaniard Yes, working on it.

**Comment by kurpievski** [comment]
closed due to inactivity
