### ISSUE TITLE
$model->tagNames not populated on update

### ISSUE THREAD

**Issue by LarryTX** [2amigos/yii2-taggable-behavior#13]
Having gotten to the point where I can save tags with the model, now when I open the update view for the model, the $model->tagNames field is not populated. I've poked around in your model and also don't find the code to add/remove/leave alone tags on update, but I may have missed it. Is this functionality build into your extension? If not, is this a feature you can add?

**Comment by tonydspaniard** [comment]
The attribute is not populated until requested first time. We thought was better than eager loading them even if you are not using it

**Comment by tonydspaniard** [comment]
For update is automatic.

**Comment by tonydspaniard** [comment]
If you have issues let me know will try to finds the issue as I did before. Those updates on the extension were not mine. 

We are on the process to update all or extensions and provide a site for their  documentation

**Comment by LarryTX** [comment]
My issue is this. As with most Yii2 applications, I've got the partial, _form.php, that includes the Selectize input field, just like in your instructions for the attribute 'tagNames'. When I open an existing record/model for update, that field is not populated. It's just blank. I've added a ```<p><strong>Current:</strong> <?= $model->howToTagsString; ?></p>``` immediately below the field to display the tag names associated with the model. (I've tried $model->tagNames, but that produces an 'array to string' error so I had to create a getter function to produce a comma delimited string for display purposes.) Without that addition, I would have no way of  knowing what tags were associated with the model. Now, suppose I wanted to change the tags associated with the model, say removing one, adding one, and leaving one untouched. How would I do that? If I enter the tags in the blank Selectize input field, is it going to take care of that?

**Comment by tonydspaniard** [comment]
Please use version tag 0.1.0. Its obvious master branch is buggy. 

Use that version on your composer file and let me know. I believe will solve your issues.

**Comment by LarryTX** [comment]
You're absolutely right! Thanks a million. Reverting to version 0.1.0 fixed that problem. That's why I always feel like it's best to ask before I go to far down the road trying to make my own (usually very crude) fixes. You're the best Tony!

**Comment by tonydspaniard** [comment]
Sorry for the hassle. I need to redactor many extensions for the new site. Will make sure everything is properly tested. Thanks for your understanding.
