### ISSUE TITLE
Selectize out of sync with Taggable

### ISSUE THREAD

**Issue by LarryTX** [2amigos/yii2-taggable-behavior#15]
Your documentation for this behavior seems to fallen behind your Selectize extension. Specifically, the instructions suggest using ```$form->field($model, 'tagNames')->widget(Selectize::className(),``` which doesn't appear to exist any more. I used ```$form->field($model, 'tagNames')->widget(SelectizeTextInput::className(),``` which appears to work fine.

I reported earlier an issue about the fact that the tag names don't appear when you open _form.php for update (hence you can't make changes to the assigned tags) nor when using 'tagNames' as a GridView column attribute in index.php, so you can't even see what tags are assigned without going to the database table to view them. This issue doesn't appear to have been fixed. It's true that, by doing as you suggested before and using version 0.1.0 of the extension does resolve the issue, but now I don't know when to actually update the extension?

Any idea when you might update this extension so that we can use the current version.

**Comment by tonydspaniard** [comment]
@LarryTX I'll do my best to do it asap. As you know we are updating our extensions and I am currently with one quite big (https://github.com/2amigos/yii2-leaflet-extension). @creocoder has taken this extension already, so I guess will be in the next days. 

Sorry for the delay, we update our extensions as fast as we can, but we wish to provide tests we ensure the extensions are solid for you guys to use.

**Comment by LarryTX** [comment]
I greatly appreciate your response, Tony. Please understand that I think your extensions are wonderful; in many ways they help make Yii2 everything that it is. I'm just trying to do planning as I make use of the extensions. And to make sure that you haven't discontinued an extension so that I need to look for an alternative. Again, not trying to rush you, just inquiring. Many, many thanks for all that you do!

**Comment by tonydspaniard** [comment]
@LarryTX The reason why I am refactoring all our extensions and add them to http://yiiwheels.com is no other but to offer the best support and quality extensions. We are not going to discontinue them but we wish to create a product (also) so things like yiifoundations.2amigos.us or yiiwheels.2amigos.com don't fall into the impossible task to be maintained again.

So worry no more... the extensions, once refactored, are here to stay for very long time.

**Comment by yiqiang** [comment]
can you confirm that this extension is now maintained by @creocoder and we have to upgrade the old version to his?

**Comment by yiqiang** [comment]
@LarryTX i dont think change to SelectizeTextInput::className() is then working, i have error "Setting unknown property: dosamigos\selectize\SelectizeTextInput::url"

**Comment by creocoder** [comment]
Fixed by 1.0.0 release
