### ISSUE TITLE
This behavior work with relation via?

### ISSUE THREAD

**Issue by zinzinday** [2amigos/yii2-taggable-behavior#17]
![untitled](https://cloud.githubusercontent.com/assets/441560/8205479/519b863e-151b-11e5-9f4a-81e365c925cf.png)
![untitled2](https://cloud.githubusercontent.com/assets/441560/8205513/84f00fbe-151b-11e5-8bd9-a25a93e56453.png)

**Comment by zinzinday** [comment]
I have test it with db mongodb, it not support junction tables, so i can not  work with method viaTable. Please review

**Comment by tonydspaniard** [comment]
@creocoder ?

**Comment by creocoder** [comment]
It was designed for usage with SQL dbms, we'll consider to make MongoDb version.

**Comment by hello-omny** [comment]
I use MySql and have same issue. I tried "via" method and got error. Once replace it by "viaTable" has no errors.
