### ISSUE TITLE
Сyrillic symbols are encoded in no understantable symbols.

### ISSUE THREAD

**Issue by mario-super** [2amigos/yii2-taggable-behavior#18]
Example:
/settings/club/list?query=%25D0%25BC%25D0%25B0%25D1%2580%25D0%25BB%25D0%25B5%25D0%25BD

Is that possible to fix that thing.

**Comment by pitonn** [comment]
I have the same problem too.

**Comment by shabarin** [comment]
As a workaround you can try urldecode($query) in controller.
