### ISSUE TITLE
$frequency cannot set to NULL value

### ISSUE THREAD

**Issue by ekawalec** [2amigos/yii2-taggable-behavior#21]
Hi, take a look at line #157:

$tag->{$this->frequency}++;

Add checking $frequency variable, please :)

**Comment by tonydspaniard** [comment]
Shouldn't the model be set to have a default value of 0 instead of NULL?

**Comment by ekawalec** [comment]
What about model without field frequency? 
11 sty 2016 16:56 Antonio Ramirez <notifications@github.com> napisał(a):Shouldn't the model be set to have a default value of 0 instead of NULL?

**Comment by tonydspaniard** [comment]
@ekawalec ok... got the point. I'll update the extension so frequency is optional.

**Comment by kurpievski** [comment]
added
