### ISSUE TITLE
Multiple instances in one model

### ISSUE THREAD

**Issue by LarryTX** [2amigos/yii2-taggable-behavior#23]
First, let me thank you for having created such an awesome extension.

I' wondering if I can implement multiple instances of Taggable in one model by using a different behavior name for each instance, like this:
```
public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'patronages' => [
                'class' => Taggable::className(),
                'relation' => 'Patronages',
                'name' => 'patronage',
                'attribute' => 'patronages'
            ],
            'types' => [
                'class' => Taggable::className(),
                'relation' => 'Types',
                'name' => 'Type',
                'attribute' => 'types'
            ],
        ]);
    }
```
When tried to do this,  it seems to store the results of data entry for the first attribute but ignores the second. I've tried debug other sources of the error, and I can't find any, I wanted to check with you on having multiple instances before I spend additional time debugging..

**Comment by tonydspaniard** [comment]
Unfortunatelly @LarryTX you cannot use methods directly due to the nature of Yii2 behaviors. 

The only workaround would be to change the internal functions and provide a different names ***OR*** getting access to the behavior functions like this: 

```php 
$model->getBehavior('patronages')->... 
```

That should work
