### ISSUE TITLE
Is it posible to define attributes name

### ISSUE THREAD

**Issue by brain2xml** [2amigos/yii2-taggable-behavior#26]
Hi. I have tag table with names **title, count**. How can you define then instead **name** and **frequency** as in extension?

**Comment by kategee** [comment]
I second that question

**Comment by kategee** [comment]
Looks like these are hardcoded:

`public $name = 'name';`
`public $frequency = 'frequency';`
`public $relation = 'tags';`

As per:
https://github.com/2amigos/yii2-taggable-behavior/blob/master/src/Taggable.php

So this would probably be a feature request

**Comment by tonydspaniard** [comment]
It should work thanks @kategee, nevertheless... Please check your rules too.
