### ISSUE TITLE
problem in update page

### ISSUE THREAD

**Issue by z-avanes** [2amigos/yii2-taggable-behavior#28]
hi
thank you for great job
i use last version and create page is ok but in update page init value dont show
but in version 0.1.0 is ok
where is problem?

**Comment by tonydspaniard** [comment]
I need a bit more information... cannot understand. 'init value'. What do you mean? code?

**Comment by z-avanes** [comment]
my problem like this issue
https://github.com/2amigos/yii2-taggable-behavior/issues/13

**Comment by tonydspaniard** [comment]
Can i see your code?

**Comment by z-avanes** [comment]
my model
`
<?php

namespace backend\models;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use dosamigos\taggable\Taggable;

use Yii;

/**
 * This is the model class for table "link".
 *
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property string $description
 * @property integer $state
 * @property integer $author_id
 * @property integer $updater_id
 * @property string $created_at
 * @property string $updated_at
 */
class Link extends \yii\db\ActiveRecord
{
    public $tagNames;
    public function behaviors()
    {
        return [
            [
                'class' => Taggable::className(),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'author_id',
                'updatedByAttribute' => 'updater_id',
            ],
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    Link::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    Link::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                // if you're using datetime instead of UNIX timestamp:
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'link';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['state', 'author_id', 'updater_id'], 'integer'],
            [['name', 'url', 'description'], 'required'],
            [['description', 'url'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['tagNames'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'url' => Yii::t('app', 'Url'),
            'description' => Yii::t('app', 'Description'),
            'state' => Yii::t('app', 'State'),
            'author_id' => Yii::t('app', 'Author ID'),
            'updater_id' => Yii::t('app', 'Updater ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     * @return LinkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new LinkQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->state = 1;
            }
            return true;
        } else {
            return false;
        }
    }

    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('link_tag', ['link_id' => 'id']);
    }
}
`

**Comment by z-avanes** [comment]
my view
`echo $form->field($model, 'tagNames')->widget(dosamigos\selectize\SelectizeTextInput::classname(), [
        'loadUrl' => '/tag/list',
        'options' => [
            'placeholder' => Yii::t('app', 'Add Tags'),
            'class' => 'form-control',
        ],
        'clientOptions' => [
            'persist' => false,
            'plugins' => ['remove_button'],
            'create' => true,
            'maxItems' => 3,
            'valueField' => 'name',
            'labelField' => 'name',
            'searchField' => ['name'],
//            'createFilter' => '$(\'#regex\').val()'
        ],
    ])->hint('Use commas to delimit zip codes')->label(Yii::t('app', 'Tag'));`

**Comment by tonydspaniard** [comment]
On your view, try this: 
```php 
echo $form->field($model, 'tagNames')->widget(dosamigos\selectize\SelectizeTextInput::classname(), [
        'loadUrl' => '/tag/list',
        'options' => [
            'placeholder' => Yii::t('app', 'Add Tags'),
            'class' => 'form-control',
        ],
        'clientOptions' => [
            'delimiter' => ',', // <----- ADD THIS! ALSO, USE MASTER AS I MADE A FIX
            'persist' => false,
            'plugins' => ['remove_button'],
            'create' => true,
            'maxItems' => 3,
            'valueField' => 'name',
            'labelField' => 'name',
            'searchField' => ['name'],
//            'createFilter' => '$(\'#regex\').val()'
        ],
    ])->hint('Use commas to delimit zip codes')->label(Yii::t('app', 'Tag'));`

**Comment by z-avanes** [comment]
noting happen 
var_dump($model->tagNames) is NULL

**Comment by tonydspaniard** [comment]
Do you mind doing the following and showing the result here? 

```php 
var_dump($model->tags); 
```

**Comment by z-avanes** [comment]
see the input value is empty 
![untitled](https://cloud.githubusercontent.com/assets/3988232/18815222/a3f67058-8336-11e6-908d-1cf576edbe31.jpg)

**Comment by z-avanes** [comment]
this is var_dump($model->tags); output

array(2) { [0]=> object(backend\models\Tag)#150 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(4) { ["id"]=> int(1) ["name"]=> string(8) "تست۲" ["description"]=> NULL ["frequency"]=> int(4) } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(4) { ["id"]=> int(1) ["name"]=> string(8) "تست۲" ["description"]=> NULL ["frequency"]=> int(4) } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } [1]=> object(backend\models\Tag)#156 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(4) { ["id"]=> int(7) ["name"]=> string(7) "تست4" ["description"]=> NULL ["frequency"]=> int(1) } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(4) { ["id"]=> int(7) ["name"]=> string(7) "تست4" ["description"]=> NULL ["frequency"]=> int(1) } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } }

**Comment by hello-omny** [comment]
Try to remove `public $tagNames;` from model `Link`, it shoud help. You render an empty field, i have a same problem.

Or, i think, you may put tags values in to $tagNames before render a Form, if needed.

**Comment by vc7deo** [comment]
i also have the same problem.but the old version 0.1.0 works fine

**Comment by exneval** [comment]
Please fix this @tonydspaniard .
I don't think we should keep using 0.1.0 since there're many improvements in newer version.

**Comment by tonydspaniard** [comment]
@exneval I try to figure out why is not working for you guys as Is perfectly working on our end and we are actually using it on projects. 

I'll check it

**Comment by tonydspaniard** [comment]
@z-avanes @vc7deo @exneval do you guys mind to test the master branch?

**Comment by tonydspaniard** [comment]
@z-avanes @vc7deo @exneval I have checked the code and just realized how bad the update was from version 0.1.0 to 1.0.1. I will fix it asap.

**Comment by tonydspaniard** [comment]
@z-avanes @vc7deo @exneval by the way, you guys do not need to use the 'tagNames' on your models. Thats why the update was confusing. 

Remove `tagNames` from your model and should work. Check the Taggable Behavior. The update makes use of the `_get` and `_set` magic methods, therefore that public attribute should be removed on the udpated version.

Look at `TaggableTest` to check how to properly set your model.

**Comment by exneval** [comment]
When removing the tagNames from model, yes the tagNames is populated with the tags, and CRUD is working fine, but there's problem when tagNames is used in search model,
when i try to call $this->tagNames, the value is null, it seems $this->load($params) wont populate the tagNames attribute or because there's no tagNames being declared in my model.
So it's hard to get the value of tagNames from the search($params) and the index will display wrong values

**Comment by tonydspaniard** [comment]
@exneval exactly, thats why I said it was a pretty bad update. I'll fix it asap.

**Comment by vc7deo** [comment]
@tonydspaniard ..I removed tagNames from the model and now its showing the tags in the update mode.
but update is not working when i remove or add one or more tags from the existing tags .its always shows the tags added in the create mode.

**Comment by tonydspaniard** [comment]
@vc7deo Thank you for the feedback. I really need to work it out back as it was. The update with magic methods is simply wrong. Please use old version in the meantime. I'll try to fix it asap.
