### ISSUE TITLE
Is it possible to use it more than one time in the same form ?

### ISSUE THREAD

**Issue by eduardo-g-silva** [2amigos/yii2-taggable-behavior#30]
Hi, 
I am trying to use the same concept of tags for categories.

I have Books with Tags and Categories (in the categories i call the name field title) 

I duplicate all the tags for categories but i can't manage to load the current categories or save when I update the record.

The tags work perfect and the categories loads, filter, add etc but doesn't save

What I am a bit confuse it is with the tagNames attribute 
$tabBook .= $form->field($model, 'tagNames')->widget(SelectizeTextInput::className(), [

because flowing the sample I only add the rule in my book model to make it work:
[['tagNames'], 'safe'],

I tried to do the same with:
[['bookCategories'], 'safe'],

but of course I get an error because bookCategories it is not defined but neither tagName.

The main problem it is when i try to get the array with the categories in the book model: 

```
public function getBookCategories() {
        $esto = $this->hasMany(BookCategory::className(), ['id' => 'category_id'])->viaTable('book_category_assn', ['book_id' => 'id']);
        return $esto;       
}
```

Do you think i need to create a $bookCategories and a function in the module to save and load the saved categories? Or it is a way to reuse this functionality from the extension?

Thanks a lot

**Comment by eduardo-g-silva** [comment]
I couldn't manage to reuse the same class with another fields so I duplicate the class and changed with the fields I needed.

**Comment by tonydspaniard** [comment]
@eduardo-g-silva as long as the attributes are different, there shouldn't be any issue at all.

**Comment by eduardo-g-silva** [comment]
@tonydspaniard hi tony sorry I come over this again but I couldn't make it work with out changing the extension.

what do you mean about different attribute?

Do I need to add something in the behaviors ?

I can only make it work if if use **tagNames** as the attribute and then i put the function with **getTags**

```
    public function getTags() {
        return $this->hasMany(Language::className(), ['id' => 'language_id'])->viaTable('user_language_assn', ['user_id' => 'user_id']);
    }
```

in the view

```
            echo '<div class="form-group field-tags">';
            echo $form->field($model->getModel('profile'), 'tagNames')->widget(SelectizeTextInput::className(), [
                'loadUrl' => ['/language/list'],
                'options' => ['class' => 'form-control tags'],
                'clientOptions' => [
                    'plugins' => ['remove_button'],
                    'valueField' => 'name',
                    'labelField' => 'name',
                    'searchField' => ['name'],
                    'autosearch' => ['on'],
                    'create' => FALSE,
                ],
            ])->hint('Use commas to separate tags');
            echo '</div>';
```

**Comment by eduardo-g-silva** [comment]
Ok I got it, looking the sorce code it make sense (you said that in the read me to see the code)

```
            [
                'class' => Taggable::className(),
                'attribute' => 'langNames',
                'relation' => 'langs',
            ],            
            [
                'class' => Taggable::className(),
                'attribute' => 'langiNames',
                'relation' => 'langis',
            ],    

```

and then the rule

 `           [['langNames','langiNames'], 'safe'],            `



the attributes I call from the view that's the confusing part because the function is call langs and not langNames as I need to use it in the view.  Probably my ignorance in relation of the whay yii handles the attribute from the model.

```
    public function getlangs() {
        return $this->hasMany(Language::className(), ['id' => 'language_id'])->viaTable('user_language_assn', ['user_id' => 'user_id']);
    }

    public function getlangis() {
        return $this->hasMany(Language::className(), ['id' => 'language_id'])->viaTable('user_language_interest_assn', ['user_id' => 'user_id']);
    }

```

and the view in case someone it is curious.....

```
            echo '<div class="form-group field-tags">';
            echo $form->field($model->getModel('profile'), 'langNames')->widget(SelectizeTextInput::className(), [
                'loadUrl' => ['/language/list'],
                'options' => ['class' => 'form-control tags'],
                'clientOptions' => [
                    'plugins' => ['remove_button'],
                    'valueField' => 'name',
                    'labelField' => 'name',
                    'searchField' => ['name'],
                    'autosearch' => ['on'],
                    'create' => FALSE,
                ],
            ]);
            echo '</div>';

            echo '<div class="form-group field-tags">';
            echo $form->field($model->getModel('profile'), 'langiNames')->widget(SelectizeTextInput::className(), [
                'loadUrl' => ['/language/list'],
                'options' => ['class' => 'form-control tags'],
                'clientOptions' => [
                    'plugins' => ['remove_button'],
                    'valueField' => 'name',
                    'labelField' => 'name',
                    'searchField' => ['name'],
                    'autosearch' => ['on'],
                    'create' => FALSE,
                ],
            ]);
            echo '</div>';

```
