### ISSUE TITLE
Additional attributes

### ISSUE THREAD

**Issue by nihaha** [2amigos/yii2-taggable-behavior#31]
Hello! Thanks for the great extension.
Is it possible to add extra value same way as "name" of the tag while adding(creating) new tags?
I have a data-alias attribute attached to all my tags, also, there is a column "alias" in my DB table 'tag'. How can I put it in while saving a model?

**Comment by tonydspaniard** [comment]
@nihaha Tags are normally added by value using some input that allows autocomplete search by name. In your case, this behavior doesn't suit  your needs as (if you look at the code) it works with those names on the input field and searches by name to find out whether they exists and if not, creates one: https://github.com/2amigos/yii2-taggable-behavior/blob/master/src/Taggable.php#L154

Nevertheless, if you are creating the alias based on their name, you can use 'afterSave' method of the model and create your alias there.

**Comment by nihaha** [comment]
Great, thank you! 
I've managed to achieve what I wanted and now my tags have names and aliases and I can treat them as categories as well.
