### ISSUE TITLE
TagNames property is not saved

### ISSUE THREAD

**Issue by kansey** [2amigos/yii2-taggable-behavior#32]
Reading https://github.com/2amigos/yii2-taggable-behavior/issues/12 did not help

**Comment by tonydspaniard** [comment]
@kansey have you set `tagNames` as `safe` on your rules?

**Comment by kansey** [comment]
The problem was that I declared tagNames as public property

**Comment by tonydspaniard** [comment]
Thank you @kansey for taking the time to show your findings.
