### ISSUE TITLE
How to filter in gridview

### ISSUE THREAD

**Issue by pkjoshi** [2amigos/yii2-taggable-behavior#36]
I have installed the extension, everything is working fine.
but couldn't get an idea how to make filter/search to work in gridview.
any documentation/guide for that?

**Comment by kurpievski** [comment]
@pkjoshi browse the official Yii2 documentation, please - you will find everything what you need there

**Comment by GermanZun** [comment]
> I have installed the extension, everything is working fine.
> but couldn't get an idea how to make filter/search to work in gridview.
> any documentation/guide for that?

Did you find anything? Thanks!
